sudo: false
language: erlang
otp_release:
  - 17.5
  - 18.0
  - 18.1
  - 18.2
  - 18.2.1
before_install:
  - pip install --user codecov
#before_script:
#  - make build-plt
script: make test
after_success:
  - bin/covertool -cover .eunit/cover.coverdata  -appname urilib -output cobertura.xml
  - codecov
